##https://devpress.csdn.net/k8s/62ebf71d19c509286f415ed0.html
##https://lyz-code.github.io/blue-book/devops/prometheus/blackbox_exporter/#http-endpoint-returning-an-error
config:
  modules:
    http_2xx:
      http:
        fail_if_not_ssl: true
        ip_protocol_fallback: false
        method: GET
        no_follow_redirects: false
        preferred_ip_protocol: ip4
        valid_http_versions:
          - HTTP/1.1
          - HTTP/2.0
        valid_status_codes:
          - 200
          - 204
      prober: http
      timeout: 15s
    http_ok:
      http:
        fail_if_not_ssl: true
        ip_protocol_fallback: false
        method: GET
        no_follow_redirects: false
        preferred_ip_protocol: ip4
        valid_http_versions:
          - HTTP/1.1
          - HTTP/2.0
        valid_status_codes:
          - 200
          - 204
          - 400
          - 401
          - 403
          - 404
          - 410
      prober: http
      timeout: 15s