prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: "default"
          resources:
            requests:
              storage: 5Gi                   
    additionalScrapeConfigs: #Blackbox exporter configs
      - job_name: prometheus-blackbox-exporter
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets: 
            - https://google.com
            - https://amazon.com
        relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
      replacement: prometheus-blackbox-exporter.monitoring:9115